### ISSUE TITLE
Switches -a and -f failing in El Capitan

### ISSUE THREAD

**Issue by elnomade** [bartobri/no-more-secrets#32] opened 2016-09-19 00:03 UTC
I followed the instructions to install no-more-secrets from source and from package (brew). Same results for both. When you run nms you get the 'encrypted' characters and nothing else, no animation and no decryption effect even when -a switch is provided.
switch "-f colour"  is also failing, no colour changing in fonts, it keeps default blue.
I tried both options in different terminal settings, including homebrew, basic and backlight. I noticed that it changes background to black only when I used "basic" settings.

Same source code works fine in linux.
No compilation error (from source) neither any installation error (from package).

OS: Mac OSX El Capitan.

**Comment by bartobri** [comment] 2016-09-19 00:07
Okay, open an issue for OS X. Just stick to installing it from brew as that
is the only approved install method.

Please include the exact commands you are typing that aren't working,
including the data you are piping in to nms, and what the result is.

Thanks

**Comment by elnomade** [comment] 2016-09-19 00:26
Command Line Options

Use the -a option to set the auto_decrypt flag. This will automatically start the decryption effect, eliminating the need for the user to press a key to start it.

ls -l / | nms -a

Use the -f option to set foreground color to either white, yellow, black, magenta, blue, green, or red - this is blue by default.

ls -l / | nms -f green

**Comment by elnomade** [comment] 2016-09-19 00:27
I tried the examples provided in the documentation.

**Comment by bartobri** [comment] 2016-09-19 03:01
> switch "-f colour" is also failing, no colour changing in fonts

This is expected behavior. The color of the font is not changed until after the characters are decrypted, not before. If you are unable to start the decryption effect, then you will not see the color setting applied.

> I noticed that it changes background to black only when I used "basic" settings.

nms has no background color setting. This is controlled by your terminal settings.

**Comment by bartobri** [comment] 2016-09-19 03:03
Ignoring the font color issue, the only issue that needs to be tested here is starting the decryption effect for OS X El Capitan.

**Comment by elnomade** [comment] 2016-09-19 03:13
The color of font is not changed when the animation and decryption effect ends. It always the default blue.

**Comment by bartobri** [comment] 2016-09-19 03:16
> The color of font is not changed when the animation and decryption effect ends.

You said in your original issue description that you can not get the encryption effect to start:

> When you run nms you get the 'encrypted' characters and nothing else, no animation and no decryption effect even when -a switch is provided.

Are you saying now that it is starting?

**Comment by elnomade** [comment] 2016-09-19 03:16
"nms -a" doesn't start automatically in OSX, I checked that it works in openSUSE. I can create a screen capture video tomorrow, showing these issues.

**Comment by elnomade** [comment] 2016-09-19 03:18
switch "-a" is not changing default behavior, even when it doesn't start automatically, you still can start it using a key

**Comment by bartobri** [comment] 2016-09-19 03:22
I am closing this issue due to it being unclear and self-contradictory.

Please, when submitting an issue, be clear, concise, and consistent, or else I can not help.

**Closed by bartobri** 2016-09-19 03:22 UTC

**Comment by elnomade** [comment] 2016-09-19 03:48
https://youtu.be/QUNjFaupQeQ
